<?
namespace Serveros\Serveros\Exceptions;

use Serveros\Serveros\Exceptions\ServerosException;

/**
 *  A base class to wrap errors generated by other PHP libraries.
 *  
 *  @class Error.WrappedError
 *  @extends ServerosError
 *  @inheritdoc
 *  @param {Error} [err] The wrapped Error
 *  @param {String} [message] A message about where the error occured.
 */
class WrappedError {
    public $e;
    public function __construct($e, $message) {
        parent::__construct($message);
        if ($e) $this->e = $e;
    }
    public function additionalInformation() {
        return [
            "rootError" => $this->e->getMessage()
        ];
    }
}
